Spring:
  # 静态资源处理
  resources:
    # 启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存相应时间，单位 秒
        max-age: 3600

    chain:
      # 资源链启动缓存，默认启动
      cache: true
      # 启动资源链，默认禁用
      enabled: true
      # 启用压缩资源（gzip,brotli），默认禁用
      compressed: true
      # 启用 h5 应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  # thymeleaf 配置
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源配置
  datasource:
    # 数据源驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/seckill
    # 用户名及密码
    username: root
    password: root1234
    # 连接池
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接出
      minimum-idle: 5
      # 空闲链接存活最大时间（默认 10 min）
      idle-timeout: 1800000
      # 最大连接出（默认 10）
      maximum-pool-size: 10
      # 自动提交（从连接池返回的连接自动提交）
      auto-commit: true
      # 连接最大存活时间（0 表示永久， 默认 30 min）
      max-lifetime: 1800000
      # 连接超时时间（默认 30 sec）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # Redis 配置
  redis:
    # 服务器地址
    host: 10.104.2.234
    # 端口
    port: 6379
    # 默认操作的数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    # 连接池配置
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间（默认-1，一直等待）
        max-wait: 10000ms
        # 最大空闲连接数
        max-idle: 200
        # 最小空闲连接数
        min-idle: 5

  # RabbitMQ 配置
  rabbitmq:
    # 服务器
    host: 10.104.2.234
    # 用户
    username: guest
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672

    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条
        prefetch: 1
        # 默认启动时启动容器
        auto-startup: true
        # 当消息被拒绝时，重新进入队列
        default-requeue-rejected: true

    template:
      retry:
        # 发布重试，默认 false
        enabled: true
        # 重试时间 默认 1000 ms
        initial-interval: 1000ms
        # 重试次数 默认 3
        max-attempts: 3
        # 重试最大时间 默认 1000 ms
        max-interval: 1000ms
        # 重试的间隔乘数 （第一次1秒，第二次2秒，第三次4秒）
        multiplier: 1


# Mybatis-plus 配置
mybatis-plus:
  # 配置 Mapper.xml 映射文件存放位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置 Mybatis 数据返回类型别名（默认为类名）
  type-aliases-package: com.xxxx.seckill.pojo

# Mybatis SQL打印（方法接口所在包，不是 Mapper.xml 所在包）
logging:
  level:
    com.xxxx.seckill.mapper: debug